### PR TITLE
Shorten multiple use statements

### PR DESCRIPTION
**Pull request by Nyholm**

### CODE REVIEW

**Comment by Zegnat** [comment]
I have zero preference here. I guess this saves some LOC? Otherwise [grouping](https://secure.php.net/manual/en/language.namespaces.importing.php#language.namespaces.importing.group) could be used to save a few bytes.

**Comment by Nyholm** [comment]
Indeed =)

I did not know about grouping. I've updated the PR

**Comment by Nyholm** [comment]
Awesome. 1030 lines now. =)

**Comment by Nyholm** [comment]
Sure, that make sense to be constant. I'll add that line now

**Comment by Zegnat** [comment]
Went through all the files in src again, and looks like all classes are either in grouped `use` statements or prefixed with `\` for root now. Nice :+1:

**Comment by Nyholm** [comment]
Great. Thanks!

**Pull request merged**
