### PR TITLE
Prepare for 1.1.0

### PR DESCRIPTION
**Pull request by Nyholm**
Blocked by #106 and #107

### CODE REVIEW

**Comment by Nyholm** [comment]
@Zegnat Could you also review the [diff](https://github.com/Nyholm/psr7/compare/1.0.1...master)? I want to have your opinion of they optimizations made in #102

**Comment by Zegnat** [comment]
LGTM. Am I right that this will also fix #94 in that is changes the type-hint? Worth adding?

**Comment by Nyholm** [comment]
Yes, please fix #94. =)

**Comment by Nyholm** [comment]
Oh, sorry @Zegnat, I read this too quickly. 

Yes, it includes a fix for #94. I've also created #109 to further explain whats happening.

**Pull request merged**
