### PR TITLE
Allow string values to FilterPort

### PR DESCRIPTION
**Pull request by Nyholm**

### CODE REVIEW

**Comment by Zegnat** [comment]
Is there a reason for removing typing again?

**Comment by Nyholm** [comment]
Yeah, All the tests failed =)

It was a mistake by me merging #24 this morning. 

The PSR specifies that a \InvalidArgument should be thrown. We generated a lot of TypeErrors.

**Comment by Nyholm** [comment]
Btw, do you have any other suggestion?

**Comment by Zegnat** [comment]
> The PSR specifies that a \InvalidArgument should be thrown. We generated a lot of TypeErrors.

Ugh, I keep forgetting we can’t just use PHP 7+ type hinting while also following the Interface and its description 🤦 Carry on. Haha.

**Pull request merged**
