### PR TITLE
Encode only reserved characters in user-info

### LINKED ISSUE #219: Escaping of user info breaks NTLM authentication
The change in #213 breaks ntml based authentication when specifying a domain.

When using ntml auth it's common to have a domain that is part of the username like this
```
curl_setopt($ch, CURLOPT_USERPWD, 'DOMAIN\username:password');
```

The slash is not suppose to be escaped and if it's the authentication fails

### PR DESCRIPTION
**Pull request by nicolas-grekas**
Fix #219

This is enough to produce non-broken URLs.

### CODE REVIEW

**Review by dbu — COMMENTED** [review]
seems all the implementations do it this way, good fix.

**Comment by dbu** [comment]
btw, you might want to mention this in the changelog. there is an edge case when people use getUserInfo and assume that the info is *not* urlencoded it will now be urlencoded...

**Comment by nicolas-grekas** [comment]
See #218 for the changelog proposal.

**Pull request merged**
