### PR TITLE
Allow the package to be installed on PHP8

### PR DESCRIPTION
**Pull request by Nyholm**

### CODE REVIEW

**Comment by mnapoli** [comment]
Hi, if it's possible to tag a new release for this that would be awesome :)

I'm checking out if PHP 8 support can be added to Bref yet.

**Comment by Nyholm** [comment]
Of course! 

https://github.com/Nyholm/psr7/releases/tag/1.3.1

**Comment by williamdes** [comment]
Interesting, but why not `^7.1 || ^ 8` ?

**Comment by mnapoli** [comment]
Awesome thanks!

**Pull request merged**
